# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Reza M. Asiyabi
email: reza.asiyabi@ed.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  Reza M. Asiyabi - AI/ML for Earth Observation Scientist
domain: reza-asiyabi.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://reza-asiyabi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: reza_m_asiyabi
github_username:  reza-asiyabi

# Build settings
# theme: minima
plugins:
  - jekyll-feed

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin    : "dark" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Author
author:
  name             : "Reza M. Asiyabi"
  avatar           : "/images/photo1682407752.jpeg"
  bio              : "Postdoctoral Research Associate"
  location         : "Edinburgh, UK"
  employer         : "The University of Edinburgh, School of GeoSciences"
  email            : "reza.asiyabi@ed.ac.uk"
  github           : "reza-asiyabi"
  googlescholar    : "https://scholar.google.com/citations?user=jKpl5lQAAAAJ&hl=en"
  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  researchgate     : "https://www.researchgate.net/profile/Reza-Mohammadi-Asiyabi"
  uri              :
  bitbucket        : 
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  gitlab           : "reza-asiyabi"
  google_plus      :
  keybase          :
  instagram        : "reza_m.asiyabi"
  impactstory      : 
  lastfm           :
  linkedin         : "reza-m-asiyabi-97b863178/"
  orcid            : "https://orcid.org/0000-0002-0162-2376"
  pinterest        : "reza_mohammadiasiyabi"
  soundcloud       :
  stackoverflow    : 
  steam            :
  tumblr           :
  twitter          : "reza_m_asiyabi"
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :
  kaggle           : 

#Site Header
header:
  image: /images/Header.jpg

# Site Footer
footer:
  links:
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/reza-asiyabi"
  - label: "Instagram"
    icon: "fab fa-fw fa-instagram"
    url: "https://instagram.com/reza_m.asiyabi?igshid=YmMyMTA2M2Y="
    
   

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

include:
  - _pages
  - files

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# hide RSS feed
atom_feed:
  hide: true


analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-DGQ7BQQ1DV"
    anonymize_ip: false # default



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
